name: mysql-shell
base: core18
version: '8.0.19'
summary: MySQL Shell
description: |
  MySQL Shell (part of MySQL Server) 8.0
  MySQL query and administration shell client and framework.
grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode
architectures:
  - build-on: amd64
  - build-on: i386
  - build-on: arm64
  - build-on: ppc64el
environment:
  LD_LIBRARY_PATH: $SNAP/lib:$SNAP/usr/lib
  PATH: $SNAP/bin:$PATH
  LC_ALL: C

apps:
  mysqlsh:
    command: bin/mysqlsh
    plugs:
      - network

parts:
  mysql-shell:
    plugin: dump
    source: https://github.com/mysql/mysql-shell
    source-type: git
    source-branch: "8.0"
    override-build: |
      # Clean out build directory until we can stop the copy in the first place
      rm -rf /root/parts/mysql-shell/build/*
      cmake ../src -DMYSQL_BUILD_DIR=/root/parts/mysql-server/build/bld -DMYSQL_SOURCE_DIR=/root/parts/mysql-server/src -DHAVE_PYTHON=1
      make -j4
      # Clean up cruft that does not need to go in the snap
      sh /root/project/scripts/cleanup-stage.sh
      snapcraftctl build
    build-packages:
      - cmake
      - gcc
      - g++
      - zip
      - libncurses5-dev
      - bison
      - pkg-config
      - libcurl4
      - libcurl4-gnutls-dev
      - libpython3-dev
      - libssl-dev
    stage-packages:
      - libasn1-8-heimdal
      - libcurl3-gnutls
      - libgssapi3-heimdal
      - libhcrypto4-heimdal
      - libheimbase1-heimdal
      - libheimntlm0-heimdal
      - libhx509-5-heimdal
      - libkrb5-26-heimdal
      - libldap-2.4-2
      - libnghttp2-14
      - libpsl5
      - libpython3.6
      - libroken18-heimdal
      - librtmp1
      - libsasl2-2
      - libwind0-heimdal
  mysql-server:
    plugin: dump
    source: https://github.com/mysql/mysql-server
    source-branch: "8.0"
    source-type: git
    override-build: |
      mkdir bld
      cd bld
      cmake .. -DWITH_SSL=system -DWITH_BOOST=boost -DDOWNLOAD_BOOST=1 -Dprotobuf_BUILD_SHARED_LIBS=OFF
      cmake --build . --target mysqlclient
      cmake --build . --target mysqlxclient
